//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeDemotivator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demotivator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demotivator()
        {
            this.DemotivatorTegs = new HashSet<DemotivatorTegs>();
        }
    
        public int Id { get; set; }
        public string DemotivatorName { get; set; }
        public System.DateTime CreatDate { get; set; }
        public string UrlDemotivator { get; set; }
        public string OriginUrlDemotivator { get; set; }
        public string HeaderString { get; set; }
        public string SecondString { get; set; }
        public string AspNetUsersId { get; set; }
        public int RatingIdDemotivator { get; set; }
        public string RatingIdUser { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemotivatorTegs> DemotivatorTegs { get; set; }
    }
}
